//真实路径，可以用作一个分类吧
package rules;
//引入实体
import com.liugs.tool.drools.bo.Order
import com.liugs.tool.base.Console

//定义规则 小于100
rule "book_discount_1"
    when
        //Order：类型约束    orgPrice < 100：属性约束
        $order:Order(orgPrice < 100) //模式匹配，到规则引擎中（工作内存）查找Order对象，条件（orgPrice < 100）
        //如果有多个条件，可用使用or 或 and连接，不写默认and
    then
        $order.setRealPrice($order.getOrgPrice());
        Console.show("成功匹配到规则一：真实价格：" + $order.getRealPrice());
end

//价格 100 到 200 的优惠 20
rule "book_discount_2"
    when
        $order:Order(100 <= orgPrice && orgPrice < 200)
    then
        $order.setRealPrice($order.getOrgPrice() - 20);
        Console.show("成功匹配到规则二：真实价格：" + $order.getRealPrice());
end

//价格 200 到 300 的优惠 50
rule "book_discount_3"
    when
        $order:Order(200 <= orgPrice && orgPrice < 300)
    then
        $order.setRealPrice($order.getOrgPrice() - 50);
        Console.show("成功匹配到规则三：真实价格：" + $order.getRealPrice());
end

//价格 300及以上 的优惠 100
rule "book_discount_4"
    when
        $order:Order($orgPrice:300 <= orgPrice)
    then
        Console.show("属性变量名：$orgPrice=" + $orgPrice);
        $order.setRealPrice($order.getOrgPrice() - 100);
        Console.show("成功匹配到规则四：真实价格：" + $order.getRealPrice());
end