package com.liugs.tool;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleTestOrderBo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.Long orderId;
    private java.lang.Long fee;
    private java.lang.Integer orderType;
    private java.lang.Integer orderSource;

    public RuleTestOrderBo() {
    }

    public java.lang.Long getOrderId() {
        return this.orderId;
    }

    public void setOrderId(java.lang.Long orderId) {
        this.orderId = orderId;
    }

    public java.lang.Long getFee() {
        return this.fee;
    }

    public void setFee(java.lang.Long fee) {
        this.fee = fee;
    }

    public java.lang.Integer getOrderType() {
        return this.orderType;
    }

    public void setOrderType(java.lang.Integer orderType) {
        this.orderType = orderType;
    }

    public java.lang.Integer getOrderSource() {
        return this.orderSource;
    }

    public void setOrderSource(java.lang.Integer orderSource) {
        this.orderSource = orderSource;
    }

    public RuleTestOrderBo(java.lang.Long orderId, java.lang.Long fee,
                           java.lang.Integer orderType, java.lang.Integer orderSource) {
        this.orderId = orderId;
        this.fee = fee;
        this.orderType = orderType;
        this.orderSource = orderSource;
    }

}